### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by briandoyle81** [Lambda-School-Labs/CS8-propertymgt#54]
Sign Up and Sign In should be two words

**Comment by briandoyle81** [comment]
and Sign Out should not be present if I am not signed in.

**Comment by codercodingthecode** [comment]
It has been fixed. On the next PR, both issues should be cleared.

**Comment by codercodingthecode** [comment]
https://github.com/Lambda-School-Labs/CS8-propertymgt/pull/56
