### ISSUE TITLE
Logging In Feedback

### ISSUE THREAD

**Issue by briandoyle81** [Lambda-School-Labs/CS8-propertymgt#55]
Button should change to "Logging in..." and become disabled when clicked
Need feedback if login fails

**Comment by codercodingthecode** [comment]
there are some updates coming up to fix that on next PR.
we added a loader to the page as well.

**Comment by codercodingthecode** [comment]
Fixed here
https://github.com/Lambda-School-Labs/CS8-propertymgt/pull/56
